endpoints:
  template: "https://default.{}-{}.prd.api.discoveryplus.com"
  default_url: "https://default.any-any.prd.api.discoveryplus.com"

client_id: "b6746ddc-7bc7-471f-a16c-f6aaf0c34d26" # androidtv
